name: Test Unfazed Prometheus

on:
  push:
    branches: ["main", "dev_pub"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    services:
      redis:
        image: redis
        ports: ['6379:6379']

    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
          allow-prereleases: true
      - name: "Install dependencies"
        run: |
          pip install uv
          uv sync
      - name: "Run format"
        run: make format
      - name: "Run Test"
        run: make test
        env:
          REDIS_URL: "redis://localhost:6379"
